#!/bin/csh

~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19228
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19229
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19230
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19231
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19232
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19233
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19234
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19235
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19236
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19237
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19238
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19239
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19347
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19355
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19356
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19357
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19358
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19359
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19360
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19361
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19362
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19363
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19364
~mabrow05/UCNA/Analyzer/source_peaks/source_peaks.exe 19365

