#!/bin/bash
# Linux/UNIX box with ssh key based login enabled
# SSH User name

echo "Generating GNU parallel command files..."

echo "Files being saved in "
pwd

##### Edit these variables to generate the script 	#####
polFlag=0
polSide=E
nbEvents=50000
##### 							#####

rm GNUParallel_commands.txt

# in this loop, set the number of .mac files you want to generate
for ((x = 0; x < 10000; x = x + 1))

do

echo './nsm '$nbEvents' '$G4EVTDIR'/n1_f_p_p'$polSide'/Evts_'$x'.root '$polFlag' '$x >> east_ALL.txt

done

echo "Done running bash script"
